# Config file for automatic testing at travis-ci.org
sudo: false  # http://docs.travis-ci.com/user/migrating-from-legacy/
language: python
env:
- FLASK_APP=autoapp.py FLASK_DEBUG=1
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
install:
  - pipenv install
  - nvm install 6.10
  - nvm use 6.10
  - npm install
before_script:
  - npm run lint
  - npm run build
script: pytest tests
