version: "2"
services:
  flask:
    build:
      context: .
      dockerfile: dockerfiles/flask/Dockerfile
    entrypoint:
      - ./app-entrypoint.sh
    user: flask
    env_file: .env
  nginx:
    restart: always
    build:
      context: .
      dockerfile: dockerfiles/nginx/Dockerfile
    depends_on:
      - flask
    ports:
      - "8000:8000" 